name: HeroCraft
version: '${project.version}'
main: com.github.itsheroph.herocraft.HeroCraft
api-version: 1.19
load: STARTUP
permissions:
  hc.multiplayerSleep.staff:
    description: "Player can modify the configuration by using the commands"
    default: op
  hc.multiplayerSleep.monster:
    description: "Player can skip the night when the monster is nearby"
    default: op
commands:
  multiplayersleep:
    description: "Player can modify the configuration by using this command"
    permission: hc.multiplayerSleep.staff
    usage: |
      /<command> enable set <true | false>
      /<command> percentage set <integer>
      /<command> day_length set <integer>
      /<command> night_length set <integer>
      /<command> night_skip_length set <integer>
      /<command> bed_enter_delay set <integer>
      /<command> chat_message set <true | false>
      /<command> action_bar_message set <true | false>
    aliases: ["mps"]
